### ISSUE TITLE
Support for Ansible Dynamic Inventory

### ISSUE THREAD

**Issue by JakeCooper** [spacelift-io/runner-ansible#8]
To run the gcp_compute inventory for dynamic inventory generation, the instance needs access to pip3 (as well as google-auth and requests)

These should come by default inside the ansible runner such that it's available for users

**Comment by JakeCooper** [comment]
I've created a PR for this. We could also have it follow the AWS convention (runner-ansible/aws/Dockerfile)

Will create a second PR supporting that and y'all can merge whichever you'd like

**Comment by peterdeme** [comment]
Thanks for the PRs! I opened a 3rd version of those with some additional maintenance stuff: https://github.com/spacelift-io/runner-ansible/pull/11

**Comment by peterdeme** [comment]
hey Jake, I merged the PR, now `spacelift/runner-ansible-gcp` is available. hope it works for you! closing this PR.
